<a href="https://colab.research.google.com/github/JulieOnIsland/DeepLearningforAI_class_2022/blob/main/coding_with_MrChollet_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The mathematical building blocks of neural networks

## A first look at a neural network

In [55]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [56]:
train_images.shape

(60000, 28, 28)

In [57]:
len(train_labels)

60000

In [58]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [59]:
import numpy as np
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [60]:
test_images.shape

(10000, 28, 28)

In [61]:
len(test_labels)

10000

In [62]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**The network architecture**

In [63]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

**The compilation step**

In [64]:
model.compile(optimizer='Adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

**Preparing the image data**

In [65]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32") / 255

**"Fitting" the model**

In [66]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 2s 3ms/step - loss: 0.2665 - accuracy: 0.9228
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1074 - accuracy: 0.9686
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0708 - accuracy: 0.9786
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0499 - accuracy: 0.9856
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0369 - accuracy: 0.9896


In [67]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 512)               401920    
                                                                 
 dense_3 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [68]:
# Calculate the number of parameters in first layer
# (input) * (dense layer #) + (bias)
784 * 512 + 512

401920

In [69]:
# Calculate the number of parameters in second layer
# (previous input) * (dense layer #) + (bias)
512 * 10 + 10

5130

**Using the model to make predictions**

In [70]:
test_digits = test_images[:10]
predictions = model.predict(test_digits)
predictions[0]

array([2.4935349e-07, 2.0500813e-07, 3.3485321e-05, 7.0644962e-04,
       5.9642502e-10, 2.1010327e-07, 1.1451890e-11, 9.9924588e-01,
       1.0875494e-06, 1.2423705e-05], dtype=float32)

In [71]:
predictions[0].argmax()

7

In [72]:
predictions[0][7]

0.9992459

In [73]:
test_labels[0]

7

**Evaluating the model on new data**

In [74]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'test accuracy: {round(test_acc, 3)}')

313/313 [==============================] - 1s 2ms/step - loss: 0.0697 - accuracy: 0.9784
test accuracy: 0.978
